system:
  develop_mode: true
  log_path: ./logs/log
  shutdown_timeout: 60

database:
  host: localhost
  port: 5432
  username: omid
  password: omid121
  db_name: chera_khube_db
  max_idle_connection: 5
  max_open_connection: 5
  max_life_time: 60

http:
  host: 0.0.0.0
  port: 8000

divar:
  api:
    get_posts: https://open-api.divar.ir/v1/open-platform/finder/user-posts
    get_post: https://open-api.divar.ir/v1/open-platform/finder/post/{{token}}
    edit_post: https://open-api.divar.ir/v1/open-platform/post/{{token}}
    delete_widget: https://open-api.divar.ir/v1/open-platform/add-ons/post/{{post_token}}
    addons: https://open-api.divar.ir/v2/open-platform/addons/post/{{post_token}}

  apartment:
    client_id: divarinow-general
    client_secret: fc893b8846daaaf8f51ee8e988ab84d124d354a73808d033ebe20569ff05b80610736ed397cd676fbe387cb2c179e4002df665a6b082d35e799a304dfafd2875
    api_key: eyJhbGciOiJSUzI1NiIsImtpZCI6InByaXZhdGVfa2V5XzIiLCJ0eXAiOiJKV1QifQ.eyJhcHBfc2x1ZyI6ImFnYWhpLXBsdXMtZ2VuZXJhbCIsImF1ZCI6InNlcnZpY2Vwcm92aWRlcnMiLCJleHAiOjE3NTY3MTYxMzcsImp0aSI6ImFmNDc5NjExLTI4YzMtMTFmMC1iZTMyLTRhNTRiMjcxYTdmNyIsImlhdCI6MTc0NjM0ODEzNywiaXNzIjoiZGl2YXIiLCJzdWIiOiJhcGlrZXkifQ.kxgCd8_cAYXCzKoCdMuAngE3ywO1XKIrSD-8lfQJYF8aYxbrVYoSUl1eSZUiGmxqtWqrVZFlGUby9E4dTMf7daq2Ilxpe8cd9JgiSur8YWzgspZvZpjrIuDcqArjUUFz-vkKN6BXgDA4GD63NN54-wanOaeyM_OqVmtiutU7wqw7UsqacpbWNwGq09B-pXwTBErJoLKqHJKbSJOKThU7aVCK_y1gIip0FblrhLDNdq0iFRvcow1SXoT7yS0kg1GwT8h3m07fmSS2UrKd6ze7PXJ4QC41EFzq9f5GDwaM3qPNjUJeqQT4msKgcZ-5-mrloNUM6oAhp1Q9YPfPDp2qFg
    redirect_uri: https://api.divarinow.ir/user/oauth
    image: 368c02f2-340b-4602-83a5-efc2b3d2407b.jpg
    scopes: USER_PHONE POST_ADDON_CREATE.

    oauth:
      base_url: https://oauth.divar.ir/oauth2/auth?response_type=%s&client_id=%s&redirect_uri=%s&scope=%s&state=%s
      response_type: code

    oauth_token:
      base_url: https://oauth.divar.ir/oauth2/token
      grant_type: authorization_code

    oauth_phone_number:
      base_url: https://open-api.divar.ir/v1/open-platform/users

  car:
    client_id: divarinow-general
    client_secret: fc893b8846daaaf8f51ee8e988ab84d124d354a73808d033ebe20569ff05b80610736ed397cd676fbe387cb2c179e4002df665a6b082d35e799a304dfafd2875
    api_key: eyJhbGciOiJSUzI1NiIsImtpZCI6InByaXZhdGVfa2V5XzIiLCJ0eXAiOiJKV1QifQ.eyJhcHBfc2x1ZyI6ImFnYWhpLXBsdXMtZ2VuZXJhbCIsImF1ZCI6InNlcnZpY2Vwcm92aWRlcnMiLCJleHAiOjE3NTY3MTYxMzcsImp0aSI6ImFmNDc5NjExLTI4YzMtMTFmMC1iZTMyLTRhNTRiMjcxYTdmNyIsImlhdCI6MTc0NjM0ODEzNywiaXNzIjoiZGl2YXIiLCJzdWIiOiJhcGlrZXkifQ.kxgCd8_cAYXCzKoCdMuAngE3ywO1XKIrSD-8lfQJYF8aYxbrVYoSUl1eSZUiGmxqtWqrVZFlGUby9E4dTMf7daq2Ilxpe8cd9JgiSur8YWzgspZvZpjrIuDcqArjUUFz-vkKN6BXgDA4GD63NN54-wanOaeyM_OqVmtiutU7wqw7UsqacpbWNwGq09B-pXwTBErJoLKqHJKbSJOKThU7aVCK_y1gIip0FblrhLDNdq0iFRvcow1SXoT7yS0kg1GwT8h3m07fmSS2UrKd6ze7PXJ4QC41EFzq9f5GDwaM3qPNjUJeqQT4msKgcZ-5-mrloNUM6oAhp1Q9YPfPDp2qFg
    redirect_uri: https://api.divarinow.ir/user/oauth
    image: 368c02f2-340b-4602-83a5-efc2b3d2407b.jpg
    scopes: USER_PHONE POST_ADDON_CREATE.

    oauth:
      base_url: https://oauth.divar.ir/oauth2/auth?response_type=%s&client_id=%s&redirect_uri=%s&scope=%s&state=%s
      response_type: code

    oauth_token:
      base_url: https://oauth.divar.ir/oauth2/token
      grant_type: authorization_code

    oauth_phone_number:
      base_url: https://open-api.divar.ir/v1/open-platform/users


app:
  salt: _E[*.61P.wA;-M>sS>Gb?@ZVd&>zp"C=A=R=p+.=K0d7CQ1R\WX;froI?wY![io`7Hk`<p=:xlK{nA<T[22H,ziR0Nv-BqweuMca+cZ1gR&D<J[6_s<,ko[Yh!aooK~C
  inquiry_cost: 150000

  inquiry_repo:
    inquiry_by_barcode_url: https://core.inquiry.ayantech.ir/webservices/Core.svc/NajiServiceVehicleAuthenticityByBarcode
    inquiry_by_green_number_url: https://core.inquiry.ayantech.ir/webservices/Core.svc/NajiServiceVehicleAuthenticityByDocumentNumber
    inquiry_api_token: D1CB46989B154B919EF76217F3435528
    owner_national_id: 002
    wallet_identifier: 111

  front_end_login_redirect: https://divarinow.ir/%s?pn=%s&t=%s&tt=%s
  front_end_purchase_redirect: https://divarinow.ir/payment?status=%d&ref_id=%s
  front_end_access_denied_redirect: https://divarinow.ir/request?state=%s&service=%s
  front_end_entry_redirect: https://divarinow.ir/entry
  llm_api_key: aa-JDpuqsYctmaNiypjpigyO1x45xn1EgfXB8hHO73T0QyGg5Zw
  llm_url: https://api.avalapis.ir/v1

  hash:
    salt: cvbn68eqeqwy
    alphabet: abcdefghijklmnopqrstuvwxyz123458760
    min_length: 6

  test: false

  kenar_redirect_base_url: https://divarinow.ir/kenar?code=%s&ref=%s
  kenar_divar_button: https://api.divarinow.ir/profile/kenar/

jwt:
  secret: ;3A4caF_kc7|nB]RZvYk7<'`2(}#sEEi?upq&miG&RdxSHF3P)l1|f6$(BQK"[lr1219EbkZ{RRo|ci3<UW~M9p!L"[4|Q7cRr_$
  expire_hour: 48

zarinpal:
  merchant_id: 670ce05f-f854-4c72-8ad9-5a565c711217
  callback_url: https://api.divarinow.ir/v1/payment/verify?user_id=%d&amount=%d&id=%d&service=%s
  sandbox: false

yektanet:
  front_redirect_url: https://divarinow.ir/user/posts?access_token=%s&service=%s
  apartment:
    redirect_url: https://api.divarinow.ir/v1/user/ads/oauth/apartment
    client_id: divarinow-general
    response_type: code
  car:
    redirect_url: https://api.divarinow.ir/v1/user/ads/oauth/car
    client_id: divarinow-general
    response_type: code